-- liquibase formatted sql
-- changeset Sameh.Adel:0001-create_initial_schema

CREATE TABLE USERS
(
    ID                 SERIAL PRIMARY KEY,
    USERNAME           VARCHAR(50)  NOT NULL UNIQUE,
    CIF                VARCHAR(20)  NOT NULL UNIQUE,
    MOBILE             VARCHAR(15)  NOT NULL UNIQUE,
    FIRST_NAME         VARCHAR(50)  NOT NULL,
    LAST_NAME          VARCHAR(50)  NOT NULL,
    PASSWORD           VARCHAR(255) NOT NULL,
    STATUS             VARCHAR(20)  NOT NULL,
    LAST_LOGIN_DATE    TIMESTAMP     NULL,
    LOGIN_TRIALS       INT          NOT NULL DEFAULT 0,
    STATUS_UPDATED_AT  TIMESTAMP     NULL,
    CREATED_AT         TIMESTAMP     NOT NULL,
    LAST_MODIFIED_DATE TIMESTAMP     NULL,
    ACTIVATED          BOOLEAN      NOT NULL DEFAULT FALSE,
    ACTIVATED_AT       TIMESTAMP     NULL
);

CREATE TABLE ROLE
(
    ID        SERIAL PRIMARY KEY,
    ROLE_NAME VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE ACCESS_URL
(
    ID      SERIAL PRIMARY KEY,
    URL     VARCHAR(255) NOT NULL,
    METHOD  VARCHAR(10)  NOT NULL,
    PRIVATE BOOLEAN      NOT NULL DEFAULT FALSE
);

CREATE TABLE ROLE_ACCESS_URL
(
    ROLE_ID INT NOT NULL,
    URL_ID  INT NOT NULL,
    PRIMARY KEY (ROLE_ID, URL_ID),
    FOREIGN KEY (ROLE_ID) REFERENCES ROLE (ID) ON DELETE CASCADE,
    FOREIGN KEY (URL_ID) REFERENCES ACCESS_URL (ID) ON DELETE CASCADE
);

CREATE TABLE USER_ROLE
(
    USER_ID INT NOT NULL,
    ROLE_ID INT NOT NULL,
    PRIMARY KEY (USER_ID, ROLE_ID),
    FOREIGN KEY (USER_ID) REFERENCES USERS (ID) ON DELETE CASCADE,
    FOREIGN KEY (ROLE_ID) REFERENCES ROLE (ID) ON DELETE CASCADE
);

CREATE TABLE SERVICE_CONFIGURATIONS
(
    ID          SERIAL PRIMARY KEY,
    CONFIG_KEY  VARCHAR(50) UNIQUE NOT NULL,
    CONFIG_VALUE VARCHAR(255) NOT NULL
);