-- liquibase formatted sql
-- changeset Sameh.Adel:0001-create_initial_schema

CREATE TABLE USERS
(
    ID       INT PRIMARY KEY IDENTITY (1,1),
    USERNAME VARCHAR(50) UNIQUE NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL,
    EMAIL    VARCHAR(100) UNIQUE NOT NULL,
    STATUS   VARCHAR(20) NOT NULL,
    CREATED_DATE  DATETIME2(6) NOT NULL,
    LAST_MODIFIED_DATE DATETIME2(6) NOT NULL,
    LAST_LOGIN_DATE DATETIME2(6),
    LOGIN_TRIES INT NOT NULL DEFAULT 0,
    LOCKED BIT NOT NULL DEFAULT 0
);

CREATE TABLE ROLES
(
    ID   INT PRIMARY KEY IDENTITY (1,1),
    NAME VARCHAR(50) UNIQUE NOT NULL
);

CREATE TABLE USER_ROLES
(
    ID     INT PRIMARY KEY IDENTITY (1,1),
    USER_ID INT NOT NULL,
    ROLE_ID INT NOT NULL,
    FOREIGN KEY (USER_ID) REFERENCES USERS (ID) ON DELETE CASCADE,
    FOREIGN KEY (ROLE_ID) REFERENCES ROLES (ID) ON DELETE CASCADE,
    UNIQUE (USER_ID, ROLE_ID)
);

CREATE TABLE URL_PERMISSIONS
(
    ID       INT PRIMARY KEY IDENTITY (1,1),
    URL      VARCHAR(255) UNIQUE NOT NULL,
    METHOD   VARCHAR(10) NOT NULL,
    IS_PUBLIC BIT NOT NULL DEFAULT 0,
    UNIQUE (URL, METHOD)
);

CREATE TABLE URL_PERMISSION_ROLES
(
    ID               INT PRIMARY KEY IDENTITY (1,1),
    URL_PERMISSION_ID INT NOT NULL,
    ROLE_ID          INT NOT NULL,
    FOREIGN KEY (URL_PERMISSION_ID) REFERENCES URL_PERMISSIONS (ID) ON DELETE CASCADE,
    FOREIGN KEY (ROLE_ID) REFERENCES ROLES (ID) ON DELETE CASCADE,
    UNIQUE (URL_PERMISSION_ID, ROLE_ID)
);

CREATE TABLE SERVICE_CONFIGURATIONS
(
    ID    INT PRIMARY KEY IDENTITY (1,1),
    NAME  VARCHAR(50) UNIQUE NOT NULL,
    VALUE VARCHAR(255) NOT NULL
);