package com.finance.common.exception;

import lombok.Getter;
import lombok.RequiredArgsConstructor;

@RequiredArgsConstructor
@Getter
public enum SharedApplicationError implements ApplicationError {

    GENERIC_ERROR("SH_GENERAL_ERROR"),
    FORBIDDEN_ERROR("SH_FORBIDDEN_ERROR"),
    UNAUTHORIZED_ERROR("SH_UNAUTHORIZED_ERROR"),
    MISSING_REQUIRED_FIELD("SH_MISSING_REQUIRED_FIELD"),
    INVALID_EMAIL("SH_INVALID_EMAIL"),
    INVALID_PHONE_NUMBER("SH_INVALID_PHONE_NUMBER"),
    INVALID_NATIONAL_ID("SH_INVALID_NATIONAL_ID"),
    INVALID_PASSPORT_NUMBER("SH_INVALID_PASSPORT_NUMBER"),
    VALIDATION_ERROR("SH_VALIDATION_ERROR"),
    CONFIGURATION_ERROR("SH_CONFIGURATION_ERROR"),
    INVALID_ALGORITHM("SHA_INVALID_ALGORITHM"),
    USER_NOT_FOUND("SH_USER_NOT_FOUND"),
    INVALID_CREDENTIALS("SH_INVALID_CREDENTIALS"),
    REFERENCE("SH_REFERENCE"),
    UNAUTHORIZED("SH_UNAUTHORIZED"),
    UNAUTHORIZED_DATA_ACCESS("SH_UNAUTHORIZED_DATA_ACCESS"),
    RESOURCE_NOT_FOUND("SH_RESOURCE_NOT_FOUND");

    private final String errorCode;
}
