// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/resources/proto/user_status_message.proto

package com.finance.common.event.schema.user;

/**
 * Protobuf enum {@code com.finance.common.event.schema.user.EventTypes}
 */
public enum EventTypes
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>STATUS_CHANGE = 0;</code>
   */
  STATUS_CHANGE(0),
  /**
   * <code>FAILED_LOGIN_ATTEMPT = 1;</code>
   */
  FAILED_LOGIN_ATTEMPT(1),
  /**
   * <code>SUCCESSFUL_LOGIN = 2;</code>
   */
  SUCCESSFUL_LOGIN(2),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>STATUS_CHANGE = 0;</code>
   */
  public static final int STATUS_CHANGE_VALUE = 0;
  /**
   * <code>FAILED_LOGIN_ATTEMPT = 1;</code>
   */
  public static final int FAILED_LOGIN_ATTEMPT_VALUE = 1;
  /**
   * <code>SUCCESSFUL_LOGIN = 2;</code>
   */
  public static final int SUCCESSFUL_LOGIN_VALUE = 2;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static EventTypes valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static EventTypes forNumber(int value) {
    switch (value) {
      case 0: return STATUS_CHANGE;
      case 1: return FAILED_LOGIN_ATTEMPT;
      case 2: return SUCCESSFUL_LOGIN;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<EventTypes>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      EventTypes> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<EventTypes>() {
          public EventTypes findValueByNumber(int number) {
            return EventTypes.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.finance.common.event.schema.user.UserStatusMessageOuterClass.getDescriptor().getEnumTypes().get(1);
  }

  private static final EventTypes[] VALUES = values();

  public static EventTypes valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private EventTypes(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:com.finance.common.event.schema.user.EventTypes)
}

