// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/resources/proto/user_status.proto

package com.finance.common.event.schema.user;

public final class UserStatusOuterClass {
  private UserStatusOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_finance_common_event_schema_user_UserStatusMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_finance_common_event_schema_user_UserStatusMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n*src/main/resources/proto/user_status.p" +
      "roto\022$com.finance.common.event.schema.us" +
      "er\032\036google/protobuf/wrappers.proto\"\331\001\n\021U" +
      "serStatusMessage\022\017\n\007user_id\030\001 \001(\003\022D\n\nnew" +
      "_status\030\002 \001(\01620.com.finance.common.event" +
      ".schema.user.UserStatus\022\016\n\006reason\030\003 \001(\t\022" +
      "\027\n\017new_status_time\030\004 \001(\003\022D\n\nevent_type\030\005" +
      " \001(\01620.com.finance.common.event.schema.u" +
      "ser.EventTypes*1\n\nUserStatus\022\n\n\006ACTIVE\020\000" +
      "\022\n\n\006LOCKED\020\001\022\013\n\007BLOCKED\020\002*9\n\nEventTypes\022" +
      "\021\n\rSTATUS_CHANGE\020\000\022\030\n\024FAILED_LOGIN_ATTEM" +
      "PT\020\001B(\n$com.finance.common.event.schema." +
      "userP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.WrappersProto.getDescriptor(),
        });
    internal_static_com_finance_common_event_schema_user_UserStatusMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_finance_common_event_schema_user_UserStatusMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_finance_common_event_schema_user_UserStatusMessage_descriptor,
        new java.lang.String[] { "UserId", "NewStatus", "Reason", "NewStatusTime", "EventType", });
    com.google.protobuf.WrappersProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
