// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/resources/proto/user_status_message.proto

package com.finance.common.event.schema.user;

/**
 * Protobuf type {@code com.finance.common.event.schema.user.UserStatusMessage}
 */
public final class UserStatusMessage extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.finance.common.event.schema.user.UserStatusMessage)
    UserStatusMessageOrBuilder {
private static final long serialVersionUID = 0L;
  // Use UserStatusMessage.newBuilder() to construct.
  private UserStatusMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private UserStatusMessage() {
    newStatus_ = 0;
    reason_ = "";
    eventType_ = 0;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new UserStatusMessage();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.finance.common.event.schema.user.UserStatusMessageOuterClass.internal_static_com_finance_common_event_schema_user_UserStatusMessage_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.finance.common.event.schema.user.UserStatusMessageOuterClass.internal_static_com_finance_common_event_schema_user_UserStatusMessage_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.finance.common.event.schema.user.UserStatusMessage.class, com.finance.common.event.schema.user.UserStatusMessage.Builder.class);
  }

  public static final int USER_ID_FIELD_NUMBER = 1;
  private long userId_ = 0L;
  /**
   * <code>int64 user_id = 1;</code>
   * @return The userId.
   */
  @java.lang.Override
  public long getUserId() {
    return userId_;
  }

  public static final int NEW_STATUS_FIELD_NUMBER = 2;
  private int newStatus_ = 0;
  /**
   * <code>.com.finance.common.event.schema.user.UserStatus new_status = 2;</code>
   * @return The enum numeric value on the wire for newStatus.
   */
  @java.lang.Override public int getNewStatusValue() {
    return newStatus_;
  }
  /**
   * <code>.com.finance.common.event.schema.user.UserStatus new_status = 2;</code>
   * @return The newStatus.
   */
  @java.lang.Override public com.finance.common.event.schema.user.UserStatus getNewStatus() {
    com.finance.common.event.schema.user.UserStatus result = com.finance.common.event.schema.user.UserStatus.forNumber(newStatus_);
    return result == null ? com.finance.common.event.schema.user.UserStatus.UNRECOGNIZED : result;
  }

  public static final int REASON_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object reason_ = "";
  /**
   * <code>string reason = 3;</code>
   * @return The reason.
   */
  @java.lang.Override
  public java.lang.String getReason() {
    java.lang.Object ref = reason_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      reason_ = s;
      return s;
    }
  }
  /**
   * <code>string reason = 3;</code>
   * @return The bytes for reason.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getReasonBytes() {
    java.lang.Object ref = reason_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      reason_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int NEW_STATUS_TIME_FIELD_NUMBER = 4;
  private long newStatusTime_ = 0L;
  /**
   * <code>int64 new_status_time = 4;</code>
   * @return The newStatusTime.
   */
  @java.lang.Override
  public long getNewStatusTime() {
    return newStatusTime_;
  }

  public static final int EVENT_TYPE_FIELD_NUMBER = 5;
  private int eventType_ = 0;
  /**
   * <code>.com.finance.common.event.schema.user.EventTypes event_type = 5;</code>
   * @return The enum numeric value on the wire for eventType.
   */
  @java.lang.Override public int getEventTypeValue() {
    return eventType_;
  }
  /**
   * <code>.com.finance.common.event.schema.user.EventTypes event_type = 5;</code>
   * @return The eventType.
   */
  @java.lang.Override public com.finance.common.event.schema.user.EventTypes getEventType() {
    com.finance.common.event.schema.user.EventTypes result = com.finance.common.event.schema.user.EventTypes.forNumber(eventType_);
    return result == null ? com.finance.common.event.schema.user.EventTypes.UNRECOGNIZED : result;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (userId_ != 0L) {
      output.writeInt64(1, userId_);
    }
    if (newStatus_ != com.finance.common.event.schema.user.UserStatus.ACTIVE.getNumber()) {
      output.writeEnum(2, newStatus_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(reason_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, reason_);
    }
    if (newStatusTime_ != 0L) {
      output.writeInt64(4, newStatusTime_);
    }
    if (eventType_ != com.finance.common.event.schema.user.EventTypes.STATUS_CHANGE.getNumber()) {
      output.writeEnum(5, eventType_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (userId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, userId_);
    }
    if (newStatus_ != com.finance.common.event.schema.user.UserStatus.ACTIVE.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(2, newStatus_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(reason_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, reason_);
    }
    if (newStatusTime_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(4, newStatusTime_);
    }
    if (eventType_ != com.finance.common.event.schema.user.EventTypes.STATUS_CHANGE.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(5, eventType_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.finance.common.event.schema.user.UserStatusMessage)) {
      return super.equals(obj);
    }
    com.finance.common.event.schema.user.UserStatusMessage other = (com.finance.common.event.schema.user.UserStatusMessage) obj;

    if (getUserId()
        != other.getUserId()) return false;
    if (newStatus_ != other.newStatus_) return false;
    if (!getReason()
        .equals(other.getReason())) return false;
    if (getNewStatusTime()
        != other.getNewStatusTime()) return false;
    if (eventType_ != other.eventType_) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + USER_ID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getUserId());
    hash = (37 * hash) + NEW_STATUS_FIELD_NUMBER;
    hash = (53 * hash) + newStatus_;
    hash = (37 * hash) + REASON_FIELD_NUMBER;
    hash = (53 * hash) + getReason().hashCode();
    hash = (37 * hash) + NEW_STATUS_TIME_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getNewStatusTime());
    hash = (37 * hash) + EVENT_TYPE_FIELD_NUMBER;
    hash = (53 * hash) + eventType_;
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.finance.common.event.schema.user.UserStatusMessage parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.finance.common.event.schema.user.UserStatusMessage parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.finance.common.event.schema.user.UserStatusMessage parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.finance.common.event.schema.user.UserStatusMessage parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.finance.common.event.schema.user.UserStatusMessage parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.finance.common.event.schema.user.UserStatusMessage parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.finance.common.event.schema.user.UserStatusMessage parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.finance.common.event.schema.user.UserStatusMessage parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.finance.common.event.schema.user.UserStatusMessage parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.finance.common.event.schema.user.UserStatusMessage parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.finance.common.event.schema.user.UserStatusMessage parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.finance.common.event.schema.user.UserStatusMessage parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.finance.common.event.schema.user.UserStatusMessage prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.finance.common.event.schema.user.UserStatusMessage}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.finance.common.event.schema.user.UserStatusMessage)
      com.finance.common.event.schema.user.UserStatusMessageOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.finance.common.event.schema.user.UserStatusMessageOuterClass.internal_static_com_finance_common_event_schema_user_UserStatusMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.finance.common.event.schema.user.UserStatusMessageOuterClass.internal_static_com_finance_common_event_schema_user_UserStatusMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.finance.common.event.schema.user.UserStatusMessage.class, com.finance.common.event.schema.user.UserStatusMessage.Builder.class);
    }

    // Construct using com.finance.common.event.schema.user.UserStatusMessage.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      userId_ = 0L;
      newStatus_ = 0;
      reason_ = "";
      newStatusTime_ = 0L;
      eventType_ = 0;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.finance.common.event.schema.user.UserStatusMessageOuterClass.internal_static_com_finance_common_event_schema_user_UserStatusMessage_descriptor;
    }

    @java.lang.Override
    public com.finance.common.event.schema.user.UserStatusMessage getDefaultInstanceForType() {
      return com.finance.common.event.schema.user.UserStatusMessage.getDefaultInstance();
    }

    @java.lang.Override
    public com.finance.common.event.schema.user.UserStatusMessage build() {
      com.finance.common.event.schema.user.UserStatusMessage result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.finance.common.event.schema.user.UserStatusMessage buildPartial() {
      com.finance.common.event.schema.user.UserStatusMessage result = new com.finance.common.event.schema.user.UserStatusMessage(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.finance.common.event.schema.user.UserStatusMessage result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.userId_ = userId_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.newStatus_ = newStatus_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.reason_ = reason_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.newStatusTime_ = newStatusTime_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.eventType_ = eventType_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.finance.common.event.schema.user.UserStatusMessage) {
        return mergeFrom((com.finance.common.event.schema.user.UserStatusMessage)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.finance.common.event.schema.user.UserStatusMessage other) {
      if (other == com.finance.common.event.schema.user.UserStatusMessage.getDefaultInstance()) return this;
      if (other.getUserId() != 0L) {
        setUserId(other.getUserId());
      }
      if (other.newStatus_ != 0) {
        setNewStatusValue(other.getNewStatusValue());
      }
      if (!other.getReason().isEmpty()) {
        reason_ = other.reason_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (other.getNewStatusTime() != 0L) {
        setNewStatusTime(other.getNewStatusTime());
      }
      if (other.eventType_ != 0) {
        setEventTypeValue(other.getEventTypeValue());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              userId_ = input.readInt64();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 16: {
              newStatus_ = input.readEnum();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 26: {
              reason_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 32: {
              newStatusTime_ = input.readInt64();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            case 40: {
              eventType_ = input.readEnum();
              bitField0_ |= 0x00000010;
              break;
            } // case 40
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private long userId_ ;
    /**
     * <code>int64 user_id = 1;</code>
     * @return The userId.
     */
    @java.lang.Override
    public long getUserId() {
      return userId_;
    }
    /**
     * <code>int64 user_id = 1;</code>
     * @param value The userId to set.
     * @return This builder for chaining.
     */
    public Builder setUserId(long value) {

      userId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>int64 user_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearUserId() {
      bitField0_ = (bitField0_ & ~0x00000001);
      userId_ = 0L;
      onChanged();
      return this;
    }

    private int newStatus_ = 0;
    /**
     * <code>.com.finance.common.event.schema.user.UserStatus new_status = 2;</code>
     * @return The enum numeric value on the wire for newStatus.
     */
    @java.lang.Override public int getNewStatusValue() {
      return newStatus_;
    }
    /**
     * <code>.com.finance.common.event.schema.user.UserStatus new_status = 2;</code>
     * @param value The enum numeric value on the wire for newStatus to set.
     * @return This builder for chaining.
     */
    public Builder setNewStatusValue(int value) {
      newStatus_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.com.finance.common.event.schema.user.UserStatus new_status = 2;</code>
     * @return The newStatus.
     */
    @java.lang.Override
    public com.finance.common.event.schema.user.UserStatus getNewStatus() {
      com.finance.common.event.schema.user.UserStatus result = com.finance.common.event.schema.user.UserStatus.forNumber(newStatus_);
      return result == null ? com.finance.common.event.schema.user.UserStatus.UNRECOGNIZED : result;
    }
    /**
     * <code>.com.finance.common.event.schema.user.UserStatus new_status = 2;</code>
     * @param value The newStatus to set.
     * @return This builder for chaining.
     */
    public Builder setNewStatus(com.finance.common.event.schema.user.UserStatus value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000002;
      newStatus_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.com.finance.common.event.schema.user.UserStatus new_status = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearNewStatus() {
      bitField0_ = (bitField0_ & ~0x00000002);
      newStatus_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object reason_ = "";
    /**
     * <code>string reason = 3;</code>
     * @return The reason.
     */
    public java.lang.String getReason() {
      java.lang.Object ref = reason_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        reason_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string reason = 3;</code>
     * @return The bytes for reason.
     */
    public com.google.protobuf.ByteString
        getReasonBytes() {
      java.lang.Object ref = reason_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        reason_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string reason = 3;</code>
     * @param value The reason to set.
     * @return This builder for chaining.
     */
    public Builder setReason(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      reason_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>string reason = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearReason() {
      reason_ = getDefaultInstance().getReason();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <code>string reason = 3;</code>
     * @param value The bytes for reason to set.
     * @return This builder for chaining.
     */
    public Builder setReasonBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      reason_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private long newStatusTime_ ;
    /**
     * <code>int64 new_status_time = 4;</code>
     * @return The newStatusTime.
     */
    @java.lang.Override
    public long getNewStatusTime() {
      return newStatusTime_;
    }
    /**
     * <code>int64 new_status_time = 4;</code>
     * @param value The newStatusTime to set.
     * @return This builder for chaining.
     */
    public Builder setNewStatusTime(long value) {

      newStatusTime_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>int64 new_status_time = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearNewStatusTime() {
      bitField0_ = (bitField0_ & ~0x00000008);
      newStatusTime_ = 0L;
      onChanged();
      return this;
    }

    private int eventType_ = 0;
    /**
     * <code>.com.finance.common.event.schema.user.EventTypes event_type = 5;</code>
     * @return The enum numeric value on the wire for eventType.
     */
    @java.lang.Override public int getEventTypeValue() {
      return eventType_;
    }
    /**
     * <code>.com.finance.common.event.schema.user.EventTypes event_type = 5;</code>
     * @param value The enum numeric value on the wire for eventType to set.
     * @return This builder for chaining.
     */
    public Builder setEventTypeValue(int value) {
      eventType_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>.com.finance.common.event.schema.user.EventTypes event_type = 5;</code>
     * @return The eventType.
     */
    @java.lang.Override
    public com.finance.common.event.schema.user.EventTypes getEventType() {
      com.finance.common.event.schema.user.EventTypes result = com.finance.common.event.schema.user.EventTypes.forNumber(eventType_);
      return result == null ? com.finance.common.event.schema.user.EventTypes.UNRECOGNIZED : result;
    }
    /**
     * <code>.com.finance.common.event.schema.user.EventTypes event_type = 5;</code>
     * @param value The eventType to set.
     * @return This builder for chaining.
     */
    public Builder setEventType(com.finance.common.event.schema.user.EventTypes value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000010;
      eventType_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.com.finance.common.event.schema.user.EventTypes event_type = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearEventType() {
      bitField0_ = (bitField0_ & ~0x00000010);
      eventType_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.finance.common.event.schema.user.UserStatusMessage)
  }

  // @@protoc_insertion_point(class_scope:com.finance.common.event.schema.user.UserStatusMessage)
  private static final com.finance.common.event.schema.user.UserStatusMessage DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.finance.common.event.schema.user.UserStatusMessage();
  }

  public static com.finance.common.event.schema.user.UserStatusMessage getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<UserStatusMessage>
      PARSER = new com.google.protobuf.AbstractParser<UserStatusMessage>() {
    @java.lang.Override
    public UserStatusMessage parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<UserStatusMessage> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<UserStatusMessage> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.finance.common.event.schema.user.UserStatusMessage getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

