apiVersion: v1
kind: Service
metadata:
  name: k8s001-uat-user-svc
spec:
  selector:
    app: k8s001-uat-user-svc
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 31111  
  type: NodePort
