apiVersion: v1
kind: Service
metadata:
  name: k8s001-uat-user-svc
spec:
  selector:
    app: k8s001-uat-user-svc
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 31111
    - protocol: TCP
      port: 1451           # Expose port 1451 for database access
      targetPort: 1451      # Forward to 1451 in the pod
  type: NodePort